[package]
name = "TurnMonitorOff"
version = "1.0.2"
edition = "2021"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
windows = { version="0.52.0", features=["Win32_Foundation", "Win32_UI", "Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
winres = "0.1.12"
