name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
